### ISSUE TITLE
Env variable for base URL

### ISSUE THREAD

**Issue by AntoineAugusti** [etalab/zammad-contact-form#3]
https://github.com/etalab/zammad-contact-form/blob/b3561394d5aae85c3758a415b13826d46e7a6381/api/index.py#L10

Curious about why you chose a constant that people can override through code change instead of an environment variable.

What's easier for reusers? Top of mind would be env variables.

**Comment by abulte** [comment]
This is totally *not* made for customization ;-) Just a friendly reminder if need be. If someone is interested we need to change that. An env var is probably fine.
